Implement blake2b
KryptonReborn/hash pull request #1
Opened 2024-06-05 17:22 UTC by HoangNguyen219

- Implement blake2b based on https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/crypto/digests/Blake2bDigest.java
- Add unit tests

2024-06-10 14:11 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Digest.kt
> +public interface Digest {
mình dùng class từ core chứ

2024-06-10 14:12 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2b.kt
> +    private var salt: ByteArray? = null // new byte[16];
coi lại comment, sao comment là new mà code lại null?

2024-06-10 14:19 UTC, iTanChi requested changes

2024-06-10 14:19 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2s.kt
> +public class Blake2s : Digest {
xem thử blake2s và 2b có dùng chung được gì ko? nên tạo class blake2 ko?

2024-06-18 01:44 UTC, iTanChi commented on library/blake2/build.gradle.kts
> +                    api(libs.kotlincrypto.core.digest)
api hay là implementation?

2024-06-18 15:27 UTC, HoangNguyen219 commented on library/blake2/build.gradle.kts
> +                    api(libs.kotlincrypto.core.digest)
Dạ em thấy implementation cũng được mà bên SHA dùng api nên em dùng theo cho đồng bộ ạ :D

2024-06-26 07:21 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2s.kt
> +    private inline fun decodeLEInt(buf: ByteArray, off: Int): Int {
check xem dùng được lib này không https://github.com/KotlinCrypto/endians

2024-06-26 07:28 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2b.kt
> +            if (i * 8 < digestLength() - 8) {
chỗ này dùng biến?

2024-06-26 17:09 UTC, HoangNguyen219 commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2s.kt
> +    private inline fun decodeLEInt(buf: ByteArray, off: Int): Int {
dạ được ạ, giờ em mới biết họ có luôn lib này 💯 em update rồi ạ

2024-06-26 17:09 UTC, HoangNguyen219 commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2b.kt
> +            if (i * 8 < digestLength() - 8) {
em update rồi ạ

2024-06-27 02:08 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2b.kt
> +            m[j] = LittleEndian.bytesToLong(
import method luôn

2024-06-27 02:12 UTC, iTanChi commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2s.kt
> +    private fun g(m1: Int, m2: Int, posA: Int, posB: Int, posC: Int, posD: Int) {
Dùng generic có được ko nhỉ? T có giá trị là Int hoặc Long

2024-06-28 13:18 UTC, HoangNguyen219 commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2b.kt
> +            m[j] = LittleEndian.bytesToLong(
Em update rồi ạ

2024-06-28 13:18 UTC, HoangNguyen219 commented on library/blake2/src/commonMain/kotlin/org/kotlincrypto/hash/blake2/Blake2s.kt
> +    private fun g(m1: Int, m2: Int, posA: Int, posB: Int, posC: Int, posD: Int) {
Em update rồi ạ

2024-06-29 16:01 UTC, iTanChi approved these changes

2024-06-30 14:46 UTC, merged